### PR TITLE
:new: Support for Big Sur

### LINKED ISSUE #88: Homebrew command error
`Error: invalid option: --all`

### LINKED ISSUE #89: Setup shell command error
`cp: /Users/akkeylab/.ssh/config: No such file or directory`

### LINKED ISSUE #90: Error: Calling brew cask install is disabled! Use brew install [--cask] instead

### LINKED ISSUE #91: Error: Cask 'java' is unavailable: No Cask with this name exists
https://github.com/AdoptOpenJDK/homebrew-openjdk

### PR DESCRIPTION
**Pull request by AkkeyLab**
fixes #88
fixes #89 
fixes #90 
fixes #91

### CODE REVIEW

File: download.sh [hunk 1]
```diff
@@ -19,7 +19,7 @@ if ! command_exists brew ; then
   echo " --------- Homebrew ----------"
   /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
   brew update
-  brew upgrade --all --cleanup
```
Comment (AkkeyLab) [inline download.sh:22]: https://github.com/AkkeyLab/mac-auto-setup/issues/88

File: setup.sh [hunk 2]
```diff
@@ -16,7 +16,7 @@ function command_exists {
 # Copy git ssh config file
 #
 echo " ------- Git SSH config ------"
-cp $(cd $(dirname ${BASH_SOURCE:-$0}); pwd)/settings/git/config ~/.ssh/config
```
Comment (AkkeyLab) [inline setup.sh:19]: https://github.com/AkkeyLab/mac-auto-setup/issues/89

File: app.sh [hunk 3]
```diff
@@ -12,36 +12,27 @@ EOS
...
-brew cask install swimat
-brew cask install spotify
-brew cask install imageoptim
-brew cask install soundflower
-brew cask install visual-studio-code
-brew cask install adobe-creative-cloud
-brew cask install gyazo
-brew cask install zoomus
-brew cask install tandem
-brew cask install discord
```
Comment (AkkeyLab) [inline app.sh:44]: https://github.com/AkkeyLab/mac-auto-setup/issues/90

File: app.sh [hunk 4]
```diff
@@ -12,36 +12,27 @@ EOS
...
+brew install --cask 1password
+brew tap AdoptOpenJDK/openjdk
+brew install --cask adoptopenjdk
```
Comment (AkkeyLab) [inline app.sh:17]: https://github.com/AkkeyLab/mac-auto-setup/issues/91
